Add New Grants endpoints
auth0/ruby-auth0 pull request #295
Opened 2021-09-03 03:57 UTC by Norio4

### Changes

- Adds new Grants endpoints

### References

- https://auth0.com/docs/api/management/v2#!/Grants/get_grants

2021-09-03 07:01 UTC, Norio4 commented
Dear developers of a great library.

I'm sorry if I'm not clear enough about this pull request.
I have created a pull request based on PR #293.

There is a Grants API in the Auth0 Management API Doc, but it was not implemented in this library. So I have added a module to call the Grants API.

Thanks!

2021-09-07 19:46 UTC, davidpatrick commented
Thank you @Norio4 for raising this :bow:  I will review this week

2021-09-08 22:37 UTC, davidpatrick requested changes
Great work here.  Just small change to include_totals

2021-09-08 22:37 UTC, davidpatrick commented on lib/auth0/api/v2/grants.rb
> +        def grants(client_id: nil, user_id: nil, audience: nil, page: nil, per_page: nil, include_totals: false)
```suggestion
        def grants(client_id: nil, user_id: nil, audience: nil, page: nil, per_page: nil, include_totals: nil)
```

2021-09-08 22:37 UTC, davidpatrick commented on spec/lib/auth0/api/v2/grants_spec.rb
> +        include_totals: false
```suggestion
        include_totals: nil
```

2021-09-08 22:37 UTC, davidpatrick commented on spec/lib/auth0/api/v2/grants_spec.rb
> +        include_totals: false
```suggestion
        include_totals: nil
```

2021-09-08 22:37 UTC, davidpatrick commented on spec/lib/auth0/api/v2/grants_spec.rb
> +        include_totals: false
```suggestion
        include_totals: nil
```

2021-09-08 22:37 UTC, davidpatrick commented on spec/lib/auth0/api/v2/grants_spec.rb
> +        include_totals: false
```suggestion
        include_totals: nil
```

2021-09-08 23:28 UTC, davidpatrick approved these changes

2021-09-08 23:28 UTC, merged